version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - DEBUG=0
      - PORT=3000
      - REDIS_IP=redis
      - MONGO_IP=mongo
    depends_on:
      - mongo
      - redis
    volumes:
      - "./:/usr/src/app"
  mongo:
    image: mongo
    volumes:
      - "./data:/data/db"
  redis:
    image: redis
    volumes:
      - "./redis_data:/data"